hackzilla_password_generator_form:
    pattern:  /
    defaults: { _controller: "HackzillaPasswordGeneratorBundle:Generator:form" }

hackzilla_password_generator_show:
    pattern:  /
    defaults: { _controller: "HackzillaPasswordGeneratorBundle:Generator:generate" }
