parameters:
    hackzilla.password_generator.class: Hackzilla\PasswordGenerator\Generator\PasswordGenerator
    hackzilla.password_generator.dummy.class: Hackzilla\PasswordGenerator\Generator\DummyPasswordGenerator
    hackzilla.password_generator.computer.class: Hackzilla\PasswordGenerator\Generator\ComputerPasswordGenerator
    hackzilla.password_generator.computer.length: 12
    hackzilla.password_generator.human.class: Hackzilla\PasswordGenerator\Generator\HumanPasswordGenerator
    hackzilla.password_generator.human.wordList: /usr/share/dict/words
    hackzilla.password_generator.human.wordSeparator: '-'
    hackzilla.password_generator.human.wordCount: 3
    hackzilla.password_generator.human.minWordLength: 4
    hackzilla.password_generator.human.maxWordLength: 99
    hackzilla.password_generator.hybrid.class: Hackzilla\PasswordGenerator\Generator\HybridPasswordGenerator
    hackzilla.password_generator.hybrid.segmentCount: 4
    hackzilla.password_generator.hybrid.segmentLength: 3
    hackzilla.password_generator.hybrid.segmentSeparator: '-'

services:
    hackzilla.password_generator:
        class: %hackzilla.password_generator.class%

    hackzilla.password_generator.dummy:
        class: %hackzilla.password_generator.dummy.class%

    hackzilla.password_generator.computer:
        class: %hackzilla.password_generator.computer.class%
        calls:
          - [setLength, [%hackzilla.password_generator.computer.length%]]

    hackzilla.password_generator.human:
        class: %hackzilla.password_generator.human.class%
        calls:
          - [setWordCount, [%hackzilla.password_generator.human.wordCount%]]
          - [setMinWordLength, [%hackzilla.password_generator.human.minWordLength%]]
          - [setMaxWordLength, [%hackzilla.password_generator.human.maxWordLength%]]
          - [setWordSeparator, [%hackzilla.password_generator.human.wordSeparator%]]
          - [setWordList, [%hackzilla.password_generator.human.wordList%]]

    hackzilla.password_generator.hybrid:
        class: %hackzilla.password_generator.hybrid.class%
        calls:
          - [setSegmentCount, [%hackzilla.password_generator.hybrid.segmentCount%]]
          - [setSegmentLength, [%hackzilla.password_generator.hybrid.segmentLength%]]
          - [setSegmentSeparator, [%hackzilla.password_generator.hybrid.segmentSeparator%]]
