parameters:
    hackzilla_password_generator.class: Hackzilla\PasswordGenerator\Generator\PasswordGenerator
    hackzilla_password_generator.dummy.class: Hackzilla\PasswordGenerator\Generator\DummyPasswordGenerator

services:
    hackzilla_password_generator:
        class: %hackzilla_password_generator.class%

    hackzilla_password_generator_dummy:
        class: %hackzilla_password_generator.dummy.class%
